name: docs 
on:
  push:
    branches:
      - main
      - dev
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # with:
        #     ref: gh-pages  # Checkout the gh-pages branch to ensure it's updated
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install \
              mkdocs-material \
              mkdocs-mermaid2-plugin \
              mike
      - run: |
          # Fetch the latest changes from gh-pages to avoid rejection
          git fetch origin gh-pages
          git merge origin/gh-pages --allow-unrelated-histories
          # Deploy all versions
          mike deploy v1.0.0 --update-aliases
          mike deploy v2.0.0 --update-aliases latest
      - run: mike set-default latest --push
      - run: mkdocs gh-deploy --force
