name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install mkdocs-material and mike
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs-material mike

    - name: Get last 3 releases
      id: get-releases
      run: |
        releases=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases | jq -r '.[].tag_name' | grep '^v' | sort -V | tail -n 3)
        echo "::set-output name=releases::$releases"

    - name: Deploy documentation
      run: |
        for release in ${{ steps.get-releases.outputs.releases }}
        do
          mike deploy $release --push
        done
        mike set-default latest --push
