name: Build MkDocs
'on':
  release:
    types:
      - published
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: '${{ github.event.release.tag_name }}'
      - name: Configure Git Credentials
        run: >
          git config user.name github-actions[bot]

          git config user.email
          41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: 'mkdocs-material-${{ env.cache_id }}'
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install \ mkdocs-material \ mkdocs-mermaid2-plugin \ mike
      - name: Deploy docs
        run: |
          # Create array of last 3 versions
          readarray -t VERSIONS < <(git tag -l 'v*' | sort -V | tail -3)
          
          # Check if we have versions
          if [ ${#VERSIONS[@]} -gt 0 ]; then
            # Deploy all except latest
            for ((i=0; i<${#VERSIONS[@]}-1; i++)); do
              VERSION=${VERSIONS[i]}
              mike deploy --push "${VERSION#v}"
            done
            
            # Deploy latest version
            LATEST=${VERSIONS[-1]}
            mike deploy --push --update-aliases "${LATEST#v}" latest
            mike set-default --push latest
          fi
