name: Release

on:
  push:
    tags:
      - v* # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    name: Release & Push to GAR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Release
      uses: huggingface/semver-release-action@latest
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    
    - name: Set LATEST_TAG environment variable
      run: |
        LATEST_TAG=$(git tag --list --sort=committerdate | tail -1)
        echo "LATEST_TAG=${LATEST_TAG}"
      shell: bash
